openapi: 3.0.0
info:
  title: API de Carritos de Compras
  version: 1.0.0
  description: API para la gestión de carritos de compras

servers:
  - url: http://localhost:3000/api/carts
    description: Servidor local

paths:
  /:
    get:
      summary: Obtener todos los carritos
      description: Recuperar una lista de todos los carritos.
      security:
        - bearerAuth: []
      tags:
        - Carritos
      responses:
        "200":
          description: Respuesta exitosa
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Cart"
        "500":
          description: Error interno del servidor
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

    post:
      summary: Crear un nuevo carrito
      description: Agregar un nuevo carrito a la base de datos.
      security:
        - bearerAuth: []
      tags:
        - Carritos
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Cart"
      responses:
        "200":
          description: Carrito creado con éxito
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Cart"
        "400":
          description: Solicitud incorrecta
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "500":
          description: Error interno del servidor
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /{cid}:
    get:
      summary: Obtener un carrito por ID
      description: Recuperar un carrito específico por su ID.
      security:
        - bearerAuth: []
      tags:
        - Carritos
      parameters:
        - in: path
          name: cid
          required: true
          schema:
            type: string
          description: ID del carrito
      responses:
        "200":
          description: Respuesta exitosa
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Cart"
        "400":
          description: Solicitud incorrecta
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "500":
          description: Error interno del servidor
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

    put:
      summary: Actualizar un carrito
      description: Actualizar los detalles de un carrito existente por ID.
      security:
        - bearerAuth: []
      tags:
        - Carritos
      parameters:
        - in: path
          name: cid
          required: true
          schema:
            type: string
          description: ID del carrito
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Cart"
      responses:
        "200":
          description: Carrito actualizado con éxito
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Cart"
        "400":
          description: Solicitud incorrecta
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "500":
          description: Error interno del servidor
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

    delete:
      summary: Eliminar un carrito
      description: Eliminar un carrito de la base de datos por ID.
      security:
        - bearerAuth: []
      tags:
        - Carritos
      parameters:
        - in: path
          name: cid
          required: true
          schema:
            type: string
          description: ID del carrito
      responses:
        "200":
          description: Carrito eliminado con éxito
        "400":
          description: Solicitud incorrecta
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "500":
          description: Error interno del servidor
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /{cid}/purchase:
    post:
      summary: Realizar la compra de los productos en un carrito
      description: Realizar la compra de los productos en un carrito específico por su ID.
      security:
        - bearerAuth: []
      tags:
        - Carritos
      parameters:
        - in: path
          name: cid
          required: true
          schema:
            type: string
          description: ID del carrito
      responses:
        "200":
          description: Compra realizada con éxito
        "400":
          description: Solicitud incorrecta
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "500":
          description: Error interno del servidor
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /{cid}/productos/{pid}:
    get:
      summary: Obtener un producto en el carrito
      description: Recuperar un producto específico dentro de un carrito por el ID del carrito y el ID del producto.
      security:
        - bearerAuth: []
      tags:
        - Carritos
      parameters:
        - in: path
          name: cid
          required: true
          schema:
            type: string
          description: ID del carrito
        - in: path
          name: pid
          required: true
          schema:
            type: string
          description: ID del producto
      responses:
        "200":
          description: Producto recuperado con éxito
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Product"
        "400":
          description: Solicitud incorrecta
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "500":
          description: Error interno del servidor
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

    post:
      summary: Agregar un producto al carrito
      description: Agregar un producto específico a un carrito por el ID del carrito y el ID del producto.
      security:
        - bearerAuth: []
      tags:
        - Carritos
      parameters:
        - in: path
          name: cid
          required: true
          schema:
            type: string
          description: ID del carrito
        - in: path
          name: pid
          required: true
          schema:
            type: string
          description: ID del producto
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Product"
      responses:
        "200":
          description: Producto agregado con éxito
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Product"
        "400":
          description: Solicitud incorrecta
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "500":
          description: Error interno del servidor
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

    put:
      summary: Actualizar un producto en el carrito
      description: Actualizar los detalles de un producto específico dentro de un carrito por el ID del carrito y el ID del producto.
      security:
        - bearerAuth: []
      tags:
        - Carritos
      parameters:
        - in: path
          name: cid
          required: true
          schema:
            type: string
          description: ID del carrito
        - in: path
          name: pid
          required: true
          schema:
            type: string
          description: ID del producto
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Product"
      responses:
        "200":
          description: Producto actualizado con éxito
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Product"
        "400":
          description: Solicitud incorrecta
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "500":
          description: Error interno del servidor
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

    delete:
      summary: Eliminar un producto del carrito
      description: Eliminar un producto específico de un carrito por el ID del carrito y el ID del producto.
      security:
        - bearerAuth: []
      tags:
        - Carritos
      parameters:
        - in: path
          name: cid
          required: true
          schema:
            type: string
          description: ID del carrito
        - in: path
          name: pid
          required: true
          schema:
            type: string
          description: ID del producto
      responses:
        "200":
          description: Producto eliminado con éxito
        "400":
          description: Solicitud incorrecta
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "500":
          description: Error interno del servidor
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    Cart:
      type: object
      properties:
        id:
          type: string
          description: El ID del carrito
        products:
          type: array
          description: La lista de productos en el carrito
          items:
            type: object
            properties:
              pid:
                type: string
                description: El ID del producto en el carrito
              quantity:
                type: number
                description: La cantidad del producto en el carrito

    Product:
      type: object
      properties:
        id:
          type: string
          description: El ID del producto
        title:
          type: string
          description: El título del producto
        description:
          type: string
          description: La descripción del producto
        price:
          type: number
          description: El precio del producto
        stock:
          type: number
          description: La cantidad en stock del producto
        photo:
          type: array
          description: Las URLs de las fotos del producto
          items:
            type: string
