const EErrors = {
	ROUNTING_ERRORS: 1,
	INVALID_TYPES_ERROR: 2,
	DATABASE_ERROR: 3,
	DATABASE_EXCEPTION: 4,
	REFERENCE_ERROR: 5,
	SYNTAX_ERROR: 6,
	RANGE_ERROR: 7,
	URI_ERROR: 8,
};

export default EErrors;
